# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - proxified

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://applantus.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_84ff73555edb4b7697581d9d90faec26 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_fe75c6e8f2b64d2aa4d14f0ce9f31773 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: applantus.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_84ff73555edb4b7697581d9d90faec26 }}/applantus.azurecr.io/proxyserver-web:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'proxified'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_80417b9984df4dcd8815ec9489ce1bac }}
        images: 'applantus.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_84ff73555edb4b7697581d9d90faec26 }}/applantus.azurecr.io/proxyserver-web:${{ github.sha }}'